In [2]:

from sklearn import datasets

loading dataset

In [3]:
iris_dataset=datasets.load_iris()

In [4]:
print(iris_dataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


checking records of the target set

In [5]:
print(iris_dataset.target_names)

['setosa' 'versicolor' 'virginica']


In [6]:
type(iris_dataset.target)

numpy.ndarray

checking top 5 records of the dataset

In [7]:
print(iris_dataset.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [8]:
type(iris_dataset)

sklearn.utils.Bunch

In [9]:
print(iris_dataset.target[0:5])

[0 0 0 0 0]


checking the shape of the dataset using shape functions

In [10]:
print(iris_dataset.data.shape)

(150, 4)


splitting data using split function


In [11]:
from sklearn.model_selection import train_test_split

splitting dataset into training set and testing set

In [13]:
x_train,x_test,y_train,y_test = train_test_split(iris_dataset.data,iris_dataset.target,test_size=0.3)

creating knn classifier

In [15]:
from sklearn.neighbors import KNeighborsClassifier

generating model for k=2

In [24]:
knn2=KNeighborsClassifier(n_neighbors=2)

training the model using training sets

In [25]:
knn2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

predicting the response for the test dataset

In [40]:
y_pred2=knn2.predict(x_test)

In [42]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred2))

Accuracy: 1.0


generating model for k=5

In [43]:
knn5=KNeighborsClassifier(n_neighbors=5)

In [44]:
knn5.fit(x_train,y_train)

KNeighborsClassifier()

predicting the response for the test dataset

In [45]:
y_pred5=knn5.predict(x_test)

In [46]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred5))

Accuracy: 1.0
